In [1]:
import pandas as pd 
import numpy as np

df1=pd.read_csv('food.csv')
df1.columns = ['food_id','title','price', 'num_orders', 'category', 'avg_rating', 'num_rating', 'tags']

df1

,food_id,title,price,num_orders,category,avg_rating,num_rating,tags
0,1,Lala Maggi,30,35,maggi,3.9,10,"veg, spicy"
1,2,Cheese Maggi,25,40,maggi,3.8,15,veg
2,3,Masala Maggi,25,10,maggi,3.0,10,"veg, spicy"
3,4,Veg Maggi,30,25,maggi,2.5,5,"veg, healthy"
4,5,Paneer Tikka,60,50,Punjabi,4.6,30,"veg, healthy"
5,6,Chicken Tikka,80,40,Punjabi,4.2,28,"meat eater, healthy, spicy"
6,7,Shawarma,70,35,Arabic,4.3,29,"meat eater,spicy,meat"
7,8,Pani puri,30,35,chat,3.9,10,"veg, spicy"
8,9,Aloo paratha,40,32,punjabi,4.3,9,veg
9,10,Paneer tikka masala,150,15,punjabi,4.5,9,veg
10,11,Hariyali paneer,140,17,punjabi,4.1,7,"veg,tandoor"
11,12,Dal,90,38,North indian,3.9,7,veg
12,13,Channa masala,70,23,punjabi,4.2,8,veg
13,14,Pav bhajji,80,17,chat,4.6,9,veg
14,15,Chettinad chicken,210,9,chettinad,4.8,9,meat eater
15,16,Mutton kebab,140,14,tandoor,4.5,8,meat eater
16,17,puttu,60,18,kerala,4.0,7,"veg,meat eater"
17,18,Crab lollipop,210,6,fast food,4.2,8,"fast food, meat eater"
18,19,Chicken kebab,140,12,tandoor,4.1,7,"meat eater,tandoor"
19,20,Dragon chicken,180,10,chinese,1.8,9,"meat eater,chinese"
20,21,Spahagetti & Meat balls,200,3,italian,4.5,8,"meat eater, pasta, italian"
21,22,Loaded fries,150,7,mexican,4.9,9,"fast food, meat eater, veg, mexican"
22,23,Empanadas,150,11,mexican,4.2,8,"fast food, meat eater,veg, mexican"
23,24,Churros,110,5,mexican,4.6,8,"dessert, mexican"
24,25,Burrito,170,8,mexican,4.3,8,"fast food, meat eater,veg, mexican"
25,26,Biriyani,240,9,chettinad,4.7,9,"chettinad, meat eater"
26,27,Kerala style prawns,240,6,kerala,3.9,6,meat eater
27,28,Beef curry,160,14,kerala,4.1,8,meat eater
28,29,Lucknow biriyani,210,8,bengali,4.7,9,meat eater
29,30,Pan fried momos,110,17,chinese,4.0,7,"veg, spicy, meat eater, chinese"
30,31,Paneer mattar,190,9,North Indian,4.6,10,"veg, spicy"
31,32,Chicken,250,23,tandoor,4.8,9,"meat eater, spicy"
32,33,Parotta,20,65,Indian,4.3,40,veg
33,34,Chapathi,15,55,Indian,4.5,25,veg
34,35,Kurkuri Bhindi,15,55,Indian,4.5,25,veg spicy
35,35,Idly,15,55,Indian,4.5,25,veg
36,36,Dosa,15,55,Indian,4.5,25,veg
37,37,Paneer butter masala,15,55,Indian,4.5,25,veg spicy
38,38,Puri,15,55,Indian,4.5,25,veg
39,39,Dim Sum,75,55,Chinese,4.5,25,meat eater
40,40,Dumplings,55,55,Chinese,4.5,25,meat eater
41,41,Chow Mein,40,55,Chinese,4.5,25,meat eater
42,42,Roast Duck,80,55,Chinese,4.5,25,meat eater
43,43,Mohinga,15,55,Burmese,4.5,25,meat eater
44,44,Shan Tofu,15,55,Burmese,4.5,25,veg
45,45,Lahpet Thoke,15,55,Burmese,4.5,25,veg
46,46,Shan rice,15,55,Burmese,4.5,25,meat eater
47,47,Shan Khao Sw,15,55,Burmese,4.5,25,veg
48,48,Polpette,15,55,Italian,4.5,25,meat eater
49,49,Pasta alla Norma,15,55,Italian,4.5,25,veg
50,50,Cassata,15,55,Italian,4.5,25,veg sweet
51,51,Granita,15,55,Italian,4.5,25,veg sweet
52,52,Porchetta,15,55,Italian,4.5,25,meat eater

In [2]:
def create_soup(x):            
    tags = x['tags'].lower().split(', ')
    tags.extend(x['title'].lower().split())
    tags.extend(x['category'].lower().split())
    return " ".join(sorted(set(tags), key=tags.index))

df1['soup'] = df1.apply(create_soup, axis=1)
df1.head(6)

,food_id,title,price,num_orders,category,avg_rating,num_rating,tags,soup
0,1,Lala Maggi,30,35,maggi,3.9,10,"veg, spicy",veg spicy lala maggi
1,2,Cheese Maggi,25,40,maggi,3.8,15,veg,veg cheese maggi
2,3,Masala Maggi,25,10,maggi,3.0,10,"veg, spicy",veg spicy masala maggi
3,4,Veg Maggi,30,25,maggi,2.5,5,"veg, healthy",veg healthy maggi
4,5,Paneer Tikka,60,50,Punjabi,4.6,30,"veg, healthy",veg healthy paneer tikka punjabi
5,6,Chicken Tikka,80,40,Punjabi,4.2,28,"meat eater, healthy, spicy",meat eater healthy spicy chicken tikka punjabi

In [3]:
from sklearn.feature_extraction.text import CountVectorizer
count = CountVectorizer(stop_words='english')

count_matrix = count.fit_transform(df1['soup'])

from sklearn.metrics.pairwise import cosine_similarity
cosine_sim = cosine_similarity(count_matrix, count_matrix)

indices_from_title = pd.Series(df1.index, index=df1['title'])
indices_from_food_id = pd.Series(df1.index, index=df1['food_id'])

In [4]:
def get_recommendations(title="", cosine_sim=cosine_sim, idx=-1):
    if idx == -1 and title != "":
        idx = indices_from_title[title]

    sim_scores = list(enumerate(cosine_sim[idx]))

    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    
    sim_scores = sim_scores[1:3]

    food_indices = [i[0] for i in sim_scores]

    return food_indices

In [5]:
df2 = df1.loc[get_recommendations(title="Shawarma")]

In [6]:
df2

,food_id,title,price,num_orders,category,avg_rating,num_rating,tags,soup
31,32,Chicken,250,23,tandoor,4.8,9,"meat eater, spicy",meat eater spicy chicken tandoor
20,21,Spahagetti & Meat balls,200,3,italian,4.5,8,"meat eater, pasta, italian",meat eater pasta italian spahagetti & meat balls

In [7]:
df2["title"]

31                    Chicken
20    Spahagetti & Meat balls
Name: title, dtype: object